### ISSUE TITLE
Data race in Run method.

### ISSUE THREAD

**Issue by carlescere** [carlescere/scheduler#4]
As suggested in [this comment](https://github.com/carlescere/scheduler/commit/c891d67e490116de10c14e86a30377ec0661442e#commitcomment-13919596) there is a data race when setting and getting isRunning.

**Comment by joeybloggs** [comment]
As an aside should add a lock in the method below and also lock the isRunning when setting it true or false here https://github.com/carlescere/scheduler/commit/c891d67e490116de10c14e86a30377ec0661442e#diff-825de533c084713290f3ee605d65aab0R179

```go
func (j *Job) IsRunning() bool {
        // j.lock
        // defer j.unlock
	return j.isRunning
}
```
